/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	gamev1 "github.com/kubegames/kubegames-operator/pkg/apis/game/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGames implements GameInterface
type FakeGames struct {
	Fake *FakeKubegamesV1
	ns   string
}

var gamesResource = schema.GroupVersionResource{Group: "kubegames.com", Version: "v1", Resource: "games"}

var gamesKind = schema.GroupVersionKind{Group: "kubegames.com", Version: "v1", Kind: "Game"}

// Get takes name of the game, and returns the corresponding game object, and an error if there is any.
func (c *FakeGames) Get(ctx context.Context, name string, options v1.GetOptions) (result *gamev1.Game, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(gamesResource, c.ns, name), &gamev1.Game{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gamev1.Game), err
}

// List takes label and field selectors, and returns the list of Games that match those selectors.
func (c *FakeGames) List(ctx context.Context, opts v1.ListOptions) (result *gamev1.GameList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(gamesResource, gamesKind, c.ns, opts), &gamev1.GameList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &gamev1.GameList{ListMeta: obj.(*gamev1.GameList).ListMeta}
	for _, item := range obj.(*gamev1.GameList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested games.
func (c *FakeGames) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(gamesResource, c.ns, opts))

}

// Create takes the representation of a game and creates it.  Returns the server's representation of the game, and an error, if there is any.
func (c *FakeGames) Create(ctx context.Context, game *gamev1.Game, opts v1.CreateOptions) (result *gamev1.Game, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(gamesResource, c.ns, game), &gamev1.Game{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gamev1.Game), err
}

// Update takes the representation of a game and updates it. Returns the server's representation of the game, and an error, if there is any.
func (c *FakeGames) Update(ctx context.Context, game *gamev1.Game, opts v1.UpdateOptions) (result *gamev1.Game, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(gamesResource, c.ns, game), &gamev1.Game{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gamev1.Game), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeGames) UpdateStatus(ctx context.Context, game *gamev1.Game, opts v1.UpdateOptions) (*gamev1.Game, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(gamesResource, "status", c.ns, game), &gamev1.Game{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gamev1.Game), err
}

// Delete takes name of the game and deletes it. Returns an error if one occurs.
func (c *FakeGames) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(gamesResource, c.ns, name, opts), &gamev1.Game{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGames) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(gamesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &gamev1.GameList{})
	return err
}

// Patch applies the patch and returns the patched game.
func (c *FakeGames) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *gamev1.Game, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(gamesResource, c.ns, name, pt, data, subresources...), &gamev1.Game{})

	if obj == nil {
		return nil, err
	}
	return obj.(*gamev1.Game), err
}
