/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	gamev1 "github.com/kubegames/kubegames-operator/pkg/apis/game/v1"
	versioned "github.com/kubegames/kubegames-operator/pkg/client/game/clientset/versioned"
	internalinterfaces "github.com/kubegames/kubegames-operator/pkg/client/game/informers/externalversions/internalinterfaces"
	v1 "github.com/kubegames/kubegames-operator/pkg/client/game/listers/game/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GameInformer provides access to a shared informer and lister for
// Games.
type GameInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.GameLister
}

type gameInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGameInformer constructs a new informer for Game type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGameInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGameInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGameInformer constructs a new informer for Game type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGameInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubegamesV1().Games(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KubegamesV1().Games(namespace).Watch(context.TODO(), options)
			},
		},
		&gamev1.Game{},
		resyncPeriod,
		indexers,
	)
}

func (f *gameInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGameInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *gameInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&gamev1.Game{}, f.defaultInformer)
}

func (f *gameInformer) Lister() v1.GameLister {
	return v1.NewGameLister(f.Informer().GetIndexer())
}
