/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/kubegames/kubegames-operator/pkg/apis/game/v1"
	scheme "github.com/kubegames/kubegames-operator/pkg/client/game/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GamesGetter has a method to return a GameInterface.
// A group's client should implement this interface.
type GamesGetter interface {
	Games(namespace string) GameInterface
}

// GameInterface has methods to work with Game resources.
type GameInterface interface {
	Create(ctx context.Context, game *v1.Game, opts metav1.CreateOptions) (*v1.Game, error)
	Update(ctx context.Context, game *v1.Game, opts metav1.UpdateOptions) (*v1.Game, error)
	UpdateStatus(ctx context.Context, game *v1.Game, opts metav1.UpdateOptions) (*v1.Game, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Game, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.GameList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Game, err error)
	GameExpansion
}

// games implements GameInterface
type games struct {
	client rest.Interface
	ns     string
}

// newGames returns a Games
func newGames(c *KubegamesV1Client, namespace string) *games {
	return &games{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the game, and returns the corresponding game object, and an error if there is any.
func (c *games) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Game, err error) {
	result = &v1.Game{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("games").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Games that match those selectors.
func (c *games) List(ctx context.Context, opts metav1.ListOptions) (result *v1.GameList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.GameList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("games").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested games.
func (c *games) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("games").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a game and creates it.  Returns the server's representation of the game, and an error, if there is any.
func (c *games) Create(ctx context.Context, game *v1.Game, opts metav1.CreateOptions) (result *v1.Game, err error) {
	result = &v1.Game{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("games").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(game).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a game and updates it. Returns the server's representation of the game, and an error, if there is any.
func (c *games) Update(ctx context.Context, game *v1.Game, opts metav1.UpdateOptions) (result *v1.Game, err error) {
	result = &v1.Game{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("games").
		Name(game.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(game).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *games) UpdateStatus(ctx context.Context, game *v1.Game, opts metav1.UpdateOptions) (result *v1.Game, err error) {
	result = &v1.Game{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("games").
		Name(game.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(game).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the game and deletes it. Returns an error if one occurs.
func (c *games) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("games").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *games) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("games").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched game.
func (c *games) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Game, err error) {
	result = &v1.Game{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("games").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
