// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: app/game/service.proto

package game

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	types "github.com/kubegames/kubegames-operator/app/game/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("app/game/service.proto", fileDescriptor_0d2fae7c4c9e5fd8) }

var fileDescriptor_0d2fae7c4c9e5fd8 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2c, 0x28, 0xd0,
	0x4f, 0x4f, 0xcc, 0x4d, 0xd5, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0xcb, 0x2e, 0x4d, 0x4a, 0x05, 0x89, 0x17, 0xc7, 0x83, 0x48, 0x29, 0x29,
	0xb8, 0xba, 0x92, 0xca, 0x82, 0xd4, 0x62, 0x08, 0x09, 0x51, 0x2b, 0xa5, 0x02, 0x92, 0xcb, 0xc9,
	0x4c, 0xd2, 0x4f, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb,
	0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x83, 0xa9, 0x52, 0x40, 0xa8, 0x4a, 0xcf, 0xd7, 0x07,
	0x8b, 0x25, 0x95, 0xa6, 0x81, 0x79, 0x10, 0x15, 0x46, 0x95, 0x5c, 0xdc, 0xee, 0x89, 0xb9, 0xa9,
	0xc1, 0x10, 0x87, 0x08, 0x65, 0x71, 0xb1, 0xb9, 0xa4, 0xe6, 0xa4, 0x96, 0xa4, 0x0a, 0xc9, 0xe9,
	0x21, 0x5c, 0x03, 0xb1, 0x18, 0x22, 0x11, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x25, 0x8f,
	0x53, 0xbe, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x49, 0xbe, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0x92,
	0x5a, 0xe2, 0x60, 0xb7, 0x95, 0x19, 0xea, 0xa7, 0x80, 0xe5, 0xf5, 0xab, 0x41, 0x7a, 0x3c, 0x5d,
	0x6a, 0x9d, 0x82, 0x4e, 0x3c, 0x94, 0x63, 0x78, 0xf0, 0x50, 0x8e, 0xf1, 0xc3, 0x43, 0x39, 0xc6,
	0x15, 0x8f, 0xe4, 0x18, 0x4f, 0x3c, 0x92, 0x63, 0xbc, 0xf0, 0x48, 0x8e, 0xf1, 0xc1, 0x23, 0x39,
	0xc6, 0x19, 0x8f, 0xe5, 0x18, 0xa2, 0x0c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3,
	0x73, 0xf5, 0xe1, 0xb6, 0x21, 0x58, 0xba, 0xf9, 0x05, 0xa9, 0x45, 0x89, 0x25, 0xf9, 0x45, 0xfa,
	0xb0, 0x80, 0x4a, 0x62, 0x03, 0xfb, 0xca, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xd9, 0xf5,
	0xa4, 0x63, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	//delete game
	Delete(ctx context.Context, in *types.DeleteRequest, opts ...grpc.CallOption) (*types.DeleteResponse, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) Delete(ctx context.Context, in *types.DeleteRequest, opts ...grpc.CallOption) (*types.DeleteResponse, error) {
	out := new(types.DeleteResponse)
	err := c.cc.Invoke(ctx, "/kubegames_game.GameService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	//delete game
	Delete(context.Context, *types.DeleteRequest) (*types.DeleteResponse, error)
}

// UnimplementedGameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (*UnimplementedGameServiceServer) Delete(ctx context.Context, req *types.DeleteRequest) (*types.DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubegames_game.GameService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).Delete(ctx, req.(*types.DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kubegames_game.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Delete",
			Handler:    _GameService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/game/service.proto",
}
