---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: games.kubegames.com
spec:
  group: kubegames.com
  versions:
  - name: v1
    served: true    
    storage: true   
    schema: 
      openAPIV3Schema:
        description: Define Games YAML Spec
        type: object
        properties:
          spec:
            type: object
            properties:
              gameID:
                type: string
              config:
                type: string
              image:
                type: string
              cpu:
                type: integer
              memory:
                type: integer
              port:
                type: integer
              commonds:
                type: array
                items:
                  type: string
              replicas:
                type: integer
          status:
            type: object
            properties:
              updateAt:
                type: string
              pods:
                type: object
                additionalProperties:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names: 
    kind: Game   
    plural: games  
    singular: game
    shortNames:
    - g

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rooms.kubegames.com
spec:
  group: kubegames.com
  versions:
  - name: v1
    served: true    
    storage: true   
    schema: 
      openAPIV3Schema:
        description: Define Room YAML Spec
        type: object
        properties:
          spec:
            type: object
            properties:
              gameID:
                type: string
              roomID:
                type: string
              config:
                type: string
              checkTimeout:
                type: boolean
              unique:
                type: boolean
          status:
            type: object
            properties:
              updateAt:
                type: string
              pods:
                type: object
                additionalProperties:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names: 
    kind: Room   
    plural: rooms  
    singular: room
    shortNames:
    - r